#!/bin/bash
#
#SBATCH --job-name=<NAME>
#SBATCH --output=<NAME>.out.log
#SBATCH --error=<NAME>.err.log
#
# Number of tasks needed for this job. Generally, used with MPI jobs
#SBATCH --ntasks=1
#SBATCH --partition=ica100
#
# Time format = HH:MM:SS, DD-HH:MM:SS
#SBATCH --time=24:00:00
#
# Number of CPUs allocated to each task.
#SBATCH --cpus-per-task=<num_cpus>
#
# Minimum memory required per allocated  CPU  in  MegaBytes.
#SBATCH --mem-per-cpu=<memory_per_cpu>
#SBATCH --gres=gpu:<num_gpus>
#SBATCH -A mdredze80_gpu
#
# Send mail to the email address when the job fails
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=<EMAIL>

# Load necessary modules
module load anaconda
module load cuda/11.8

source ~/.bashrc

conda activate quickllm

module list

python --version
which python

export TRANSFORMERS_CACHE="/scratch4/mdredze1/huggingface_cache/transformers"

# Run the Python script
python prompts_test.py --config config.toml
